# Generated by Django 5.1.2 on 2024-11-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='title')),
                ('amount', models.IntegerField(verbose_name='title')),
                ('schedule', models.CharField(max_length=50)),
                ('schedule_custom', models.CharField(blank=True, max_length=100, null=True, verbose_name='chedule_custom')),
                ('deadline', models.CharField(max_length=50, verbose_name='deadline')),
                ('deadline_custom', models.DateField(verbose_name='deadline')),
            ],
        ),
    ]
