# Generated by Django 5.1.2 on 2024-11-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_cost', '0002_remove_fixedcost_schedule_custom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedcost',
            old_name='deadline_custom',
            new_name='custom_deadline',
        ),
    ]
