# Generated by Django 5.1.2 on 2024-11-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_cost', '0003_rename_deadline_custom_fixedcost_custom_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedcost',
            name='custom_schedule',
            field=models.DateField(verbose_name='chedule_custom'),
        ),
        migrations.AlterField(
            model_name='fixedcost',
            name='deadline',
            field=models.CharField(choices=[('P', 'permanantly'), ('C', 'custom')], default='P', max_length=50, verbose_name='deadline'),
        ),
    ]
