# Generated by Django 5.1.2 on 2024-11-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_cost', '0007_alter_fixedcost_deadline_alter_fixedcost_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedcost',
            name='custom_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='custom_deadline'),
        ),
    ]
