# Generated by Django 5.1.2 on 2024-11-22 09:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_admin_user_premum_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=False, verbose_name='Is Author'),
        ),
        migrations.AlterField(
            model_name='user',
            name='premum_user',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Is Premum Until'),
        ),
    ]
