# Generated by Django 5.1.2 on 2024-11-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incom',
            new_name='Income',
        ),
    ]
