# Generated by Django 5.1.2 on 2024-12-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_remove_expense_goal_remove_income_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense_goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='amount')),
            ],
        ),
        migrations.CreateModel(
            name='income_goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='amount')),
            ],
        ),
    ]
