# Generated by Django 5.1.2 on 2024-12-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_rename_expense_goal_incomegoal_expensegoal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('month', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
