# Generated by Django 5.1.2 on 2024-12-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_saved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saved',
            old_name='month',
            new_name='date_month',
        ),
    ]
