# Generated by Django 5.1.2 on 2024-12-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_rename_month_saved_date_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saved',
            old_name='date_month',
            new_name='date',
        ),
    ]
