# Generated by Django 5.1.2 on 2024-12-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0018_saved_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
