# Generated by Django 5.1.2 on 2024-12-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_alter_saved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved',
            name='percentage',
            field=models.IntegerField(null=True, verbose_name='percentage'),
        ),
    ]
