# Generated by Django 5.1.2 on 2024-11-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='fname',
            field=models.CharField(max_length=50, verbose_name='first name'),
        ),
    ]
